import type { NodeTypeDefinition } from "./types";

type CatalogEntry = {
  type: string;
  label: string;
  description: string;
  group: "Core" | "Triggers";
  icon: string;
  outputs?: string[];
};

const triggerTypes = new Set([
  "activationTrigger", "chatTrigger", "emailTrigger", "errorTrigger", "executeWorkflowTrigger",
  "localFileTrigger", "manualTrigger", "mcpServerTrigger", "microsoftAgent365Trigger", "n8nFormTrigger",
  "n8nTrigger", "rssFeedTrigger", "schedule", "simulateTrigger", "sseTrigger", "start", "webhook",
  "workflowTrigger", "cron", "interval",
]);

const entries: CatalogEntry[] = [
  ["activationTrigger", "Activation Trigger", "Start when a workflow is activated.", "Triggers", "sparkles"],
  ["aggregate", "Aggregate", "Collect values from multiple items into one result.", "Core", "merge"],
  ["aiTransform", "AI Transform", "Transform text or structured data with an AI instruction.", "Core", "sparkles"],
  ["chat", "Chat", "Send or process a chat message in a workflow.", "Core", "chat"],
  ["chatTrigger", "Chat Trigger", "Start a workflow from a chat message.", "Triggers", "chat"],
  ["code", "Code", "Run isolated JavaScript against workflow input.", "Core", "code"],
  ["compareDatasets", "Compare Datasets", "Compare two item collections and emit differences.", "Core", "split"],
  ["compression", "Compression", "Compress or decompress payloads and files.", "Core", "database"],
  ["convertToFile", "Convert to File", "Convert structured data into a downloadable file.", "Core", "file"],
  ["convertBinary", "Convert to/from binary data", "Convert binary payloads to and from encoded data.", "Core", "file"],
  ["cron", "Cron", "Start a workflow on a cron expression.", "Triggers", "clock"],
  ["crypto", "Crypto", "Hash, encode, decode, or sign data.", "Core", "shield"],
  ["dataTable", "Data table", "Create and manipulate tabular workflow data.", "Core", "table"],
  ["dateTime", "Date & Time", "Parse, format, compare, or modify dates and times.", "Core", "clock"],
  ["e2eTest", "E2E Test", "Run a workflow-level end-to-end test assertion.", "Core", "check"],
  ["set", "Edit Fields (Set)", "Create, update, remove, and map fields.", "Core", "pencil"],
  ["editImage", "Edit Image", "Resize, transform, or annotate an image payload.", "Core", "image"],
  ["emailTrigger", "Email Trigger (IMAP)", "Start when a new email arrives in an IMAP inbox.", "Triggers", "mail"],
  ["errorTrigger", "Error Trigger", "Start a workflow when another workflow fails.", "Triggers", "warning"],
  ["executeCommand", "Execute Command", "Run an approved server command through the worker.", "Core", "terminal"],
  ["executeSubWorkflow", "Execute Sub-workflow", "Invoke another Vorrex workflow and wait for its result.", "Core", "workflow"],
  ["executeWorkflowTrigger", "Execute Workflow Trigger", "Start when invoked by another workflow.", "Triggers", "workflow"],
  ["executionData", "Execution Data", "Attach searchable metadata to an execution.", "Core", "database"],
  ["extractFromFile", "Extract from File", "Extract text or structured content from a file.", "Core", "file"],
  ["filter", "Filter", "Keep only items that match conditions.", "Core", "filter"],
  ["ftp", "FTP", "Upload, download, or list files over FTP/SFTP.", "Core", "upload"],
  ["function", "Function", "Run a reusable JavaScript transformation.", "Core", "code"],
  ["functionItem", "Function Item", "Transform each item independently with JavaScript.", "Core", "code"],
  ["git", "Git", "Clone, inspect, or update a Git repository.", "Core", "git"],
  ["html", "HTML", "Generate HTML from workflow data.", "Core", "html"],
  ["htmlExtract", "HTML Extract", "Extract fields from HTML using selectors.", "Core", "html"],
  ["httpRequest", "HTTP Request", "Call any HTTP or REST endpoint.", "Core", "globe"],
  ["icalendar", "iCalendar", "Create or parse iCalendar events.", "Core", "calendar"],
  ["if", "If", "Route items through true and false branches.", "Core", "branch", ["true", "false"]],
  ["interval", "Interval", "Start a workflow at a fixed interval.", "Triggers", "clock"],
  ["itemLists", "Item Lists", "Split, concatenate, or aggregate item lists.", "Core", "list"],
  ["limit", "Limit", "Limit the number of items passed downstream.", "Core", "filter"],
  ["localFileTrigger", "Local File Trigger", "Start when a permitted local file changes.", "Triggers", "file"],
  ["loop", "Loop Over Items (Split in Batches)", "Process items in controlled batches.", "Core", "loop", ["loop", "done"]],
  ["manualTrigger", "Manual Trigger", "Start a workflow from the builder Run action.", "Triggers", "cursorClick"],
  ["markdown", "Markdown", "Render or transform Markdown content.", "Core", "fileText"],
  ["mcpServerTrigger", "MCP Server Trigger", "Start when an MCP tool call is received.", "Triggers", "server"],
  ["merge", "Merge", "Join data from multiple upstream branches.", "Core", "merge"],
  ["microsoftAgent365Trigger", "Microsoft Agent 365 Trigger", "Start from a Microsoft Agent 365 event.", "Triggers", "bot"],
  ["n8n", "n8n", "Call or exchange data with an n8n instance.", "Core", "workflow"],
  ["n8nForm", "n8n Form", "Create or submit a form-compatible payload.", "Core", "form"],
  ["n8nFormTrigger", "n8n Form Trigger", "Start from a submitted n8n-style form.", "Triggers", "form"],
  ["n8nTrigger", "n8n Trigger", "Start from an n8n event or webhook.", "Triggers", "webhook"],
  ["noOp", "No Operation, do nothing", "Pass input through unchanged.", "Core", "noop"],
  ["readBinaryFile", "Read Binary File", "Read one permitted file into binary data.", "Core", "file"],
  ["readBinaryFiles", "Read Binary Files", "Read multiple permitted files into binary data.", "Core", "file"],
  ["readPdf", "Read PDF", "Extract text and metadata from a PDF.", "Core", "file"],
  ["readWriteFiles", "Read/Write Files from Disk", "Read or write files through an allowlisted worker path.", "Core", "file"],
  ["removeDuplicates", "Remove Duplicates", "Remove repeated items using selected fields.", "Core", "filter"],
  ["renameKeys", "Rename Keys", "Rename object keys without changing values.", "Core", "pencil"],
  ["respondToWebhook", "Respond to Webhook", "Return a response to the originating webhook request.", "Core", "webhook"],
  ["rssFeedTrigger", "RSS Feed Trigger", "Start when a feed publishes a new item.", "Triggers", "rss"],
  ["rssRead", "RSS Read", "Read and parse an RSS or Atom feed.", "Core", "rss"],
  ["schedule", "Schedule Trigger", "Start a workflow on a schedule.", "Triggers", "clock"],
  ["sendEmail", "Send Email", "Send an email through a configured SMTP account.", "Core", "mail"],
  ["simulate", "Simulate", "Generate deterministic sample data for testing.", "Core", "sparkles"],
  ["simulateTrigger", "Simulate Trigger", "Start a workflow with deterministic sample data.", "Triggers", "sparkles"],
  ["sort", "Sort", "Sort items by one or more fields.", "Core", "sort"],
  ["splitOut", "Split Out", "Expand an array field into separate items.", "Core", "split"],
  ["spreadsheetFile", "Spreadsheet File", "Read or write CSV/XLSX spreadsheet data.", "Core", "spreadsheet"],
  ["sseTrigger", "SSE Trigger", "Start from a server-sent event stream.", "Triggers", "webhook"],
  ["ssh", "SSH", "Run an approved command or transfer data over SSH.", "Core", "terminal"],
  ["start", "Start", "Start a workflow from its initial entry point.", "Triggers", "cursorClick"],
  ["stickyNote", "Sticky Note", "Add a visual note to the workflow canvas.", "Core", "notes"],
  ["stopAndError", "Stop and Error", "Stop the current run with a controlled error.", "Core", "warning"],
  ["summarize", "Summarize", "Summarize a collection of items or text.", "Core", "sparkles"],
  ["switch", "Switch", "Route items across multiple conditions.", "Core", "branch", ["0", "1", "2"]],
  ["totp", "TOTP", "Generate or verify time-based one-time passwords.", "Core", "shield"],
  ["trackTimeSaved", "Track Time Saved", "Record estimated time saved by an automation.", "Core", "clock"],
  ["wait", "Wait", "Pause until a time, event, or resume signal.", "Core", "wait"],
  ["webhook", "Webhook", "Start a workflow from an incoming HTTP request.", "Triggers", "webhook"],
  ["workflowTrigger", "Workflow Trigger", "Start when another workflow invokes this one.", "Triggers", "workflow"],
  ["writeBinaryFile", "Write Binary File", "Write binary data to a permitted file path.", "Core", "file"],
  ["xml", "XML", "Parse or generate XML documents.", "Core", "xml"],
].map(([type, label, description, group, icon, outputs]) => ({ type, label, description, group, icon, outputs } as CatalogEntry));

const categoryFor = (entry: CatalogEntry): "trigger" | "core" => entry.group === "Triggers" || triggerTypes.has(entry.type) ? "trigger" : "core";

export const CORE_NODE_CATALOG: NodeTypeDefinition[] = entries.map((entry) => ({
  type: entry.type,
  label: entry.label,
  category: categoryFor(entry),
  subcategory: entry.group === "Triggers" ? "Entry points" : "Core",
  description: entry.description,
  icon: entry.icon,
  iconKind: "outline",
  inputs: categoryFor(entry) === "trigger" ? [] : [{ id: "main", label: "Input" }],
  outputs: (entry.outputs || ["main"]).map((id) => ({ id, label: id === "main" ? "Output" : id })),
  defaultConfig: {},
  configFields: [],
  groups: [entry.group],
  image: "/node-icons/core.svg",
  implementationStatus: "stub",
}));
